// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'

    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPD2rLWY3Nvbs3cW19-SkCQ7NtfeIr_xk',
    appId: '1:585806474023:web:1eb6cd2f2a2166704c1702',
    messagingSenderId: '585806474023',
    projectId: 'jamia-2bcc1',
    authDomain: 'jamia-2bcc1.firebaseapp.com',
    storageBucket: 'jamia-2bcc1.appspot.com',
    measurementId: 'G-0GXW0ST5VC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4XvaOSJyztap5bQQWau-_kS-nu2MKR7o',
    appId: '1:585806474023:android:ec595ecc429df5314c1702',
    messagingSenderId: '585806474023',
    projectId: 'jamia-2bcc1',
    storageBucket: 'jamia-2bcc1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtIWAfh_kcCwiPeuzMCRlT9qp-rk8xric',
    appId: '1:585806474023:ios:bb0109b359e3d5524c1702',
    messagingSenderId: '585806474023',
    projectId: 'jamia-2bcc1',
    storageBucket: 'jamia-2bcc1.appspot.com',
    iosClientId: '585806474023-ap0rg438a8aspf9aig985mlghl22e6dt.apps.googleusercontent.com',
    iosBundleId: 'com.example.sprint',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtIWAfh_kcCwiPeuzMCRlT9qp-rk8xric',
    appId: '1:585806474023:ios:bb0109b359e3d5524c1702',
    messagingSenderId: '585806474023',
    projectId: 'jamia-2bcc1',
    storageBucket: 'jamia-2bcc1.appspot.com',
    iosClientId: '585806474023-ap0rg438a8aspf9aig985mlghl22e6dt.apps.googleusercontent.com',
    iosBundleId: 'com.example.sprint',
  );
}
